services:
  web:
    container_name: bluepeak-web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8001
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    depends_on:
      - api
    command: npm run dev

  api:
    container_name: bluepeak-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"  
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: db
      NODE_ENV: development
      JWT_SECRET: super-secret
      REACT_CLIENT_URL: http://localhost:5173  
    volumes:
      - ./backend:/app
      - backend-node-modules:/app/node_modules
    depends_on:
      - db
    command: npm run dev

  db:
    image: postgres:17.5-alpine
    container_name: bluepeak-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - bluepeak-data:/var/lib/postgresql/data
      - ./backend/database:/docker-entrypoint-initdb.d
    restart: always

volumes:
  bluepeak-data:
  backend-node-modules:
  frontend-node-modules:
