services:
  web:
    container_name: bluepeak-web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8001
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    depends_on:
      - api-secure
    command: npm run dev

  api-secure:
    container_name: bluepeak-api-secure
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      DB_HOST: db-secure
      DB_PORT: 5432
      DB_USER: user_secure
      DB_PASSWORD: password_secure
      DB_NAME: db_secure
      NODE_ENV: development
      JWT_SECRET: production-secret
    volumes:
      - ./backend:/app
      - backend-node-modules:/app/node_modules
    depends_on:
      - db-secure
    command: npm run dev

  db-secure:
    container_name: bluepeak-db-secure
    image: postgres:17
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: user_secure
      POSTGRES_PASSWORD: password_secure
      POSTGRES_DB: db_secure
    volumes:
      - bluepeak-secure:/var/lib/postgresql/data
      - ./backend/database:/docker-entrypoint-initdb.d
    restart: always

volumes:
  bluepeak-secure:
  backend-node-modules:
  frontend-node-modules:
